[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "uvicorn server:app --reload --port 8000"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"